export const chatUsers = [{
  nick: "yochoi",
  avatar_url: `https://cdn.intra.42.fr/users/medium_yochoi.png`,
  position: "owner"
}, {
  nick: "donglee",
  avatar_url: `https://cdn.intra.42.fr/users/medium_donglee.jpg`,
  position: "admin"
}, {
  nick: "jinwkim",
  avatar_url: `https://cdn.intra.42.fr/users/medium_jinwkim.jpg`,
  position: "admin"
}, {
  nick: "hna",
  avatar_url: `https://cdn.intra.42.fr/users/medium_hna.jpg`,
  position: ""
}, {
  nick: "jinbkim",
  avatar_url: `https://cdn.intra.42.fr/users/medium_jinbkim.jpg`,
  position: "mute"
}, {
  nick: "jinbkim",
  avatar_url: `https://cdn.intra.42.fr/users/medium_jinbkim.jpg`,
  position: "mute"
}, {
  nick: "jinbkim",
  avatar_url: `https://cdn.intra.42.fr/users/medium_jinbkim.jpg`,
  position: "mute"
}, {
  nick: "jinbkim",
  avatar_url: `https://cdn.intra.42.fr/users/medium_jinbkim.jpg`,
  position: "mute"
}, {
  nick: "jinbkim",
  avatar_url: `https://cdn.intra.42.fr/users/medium_jinbkim.jpg`,
  position: "mute"
}, {
  nick: "jinbkim",
  avatar_url: `https://cdn.intra.42.fr/users/medium_jinbkim.jpg`,
  position: "mute"
}, {
  nick: "jinbkim",
  avatar_url: `https://cdn.intra.42.fr/users/medium_jinbkim.jpg`,
  position: "mute"
}, {
  nick: "jinbkim",
  avatar_url: `https://cdn.intra.42.fr/users/medium_jinbkim.jpg`,
  position: "mute"
}, {
  nick: "jinbkim",
  avatar_url: `https://cdn.intra.42.fr/users/medium_jinbkim.jpg`,
  position: "mute"
}, {
  nick: "jinbkim",
  avatar_url: `https://cdn.intra.42.fr/users/medium_jinbkim.jpg`,
  position: "mute"
}, {
  nick: "jinbkim",
  avatar_url: `https://cdn.intra.42.fr/users/medium_jinbkim.jpg`,
  position: "mute"
}, {
  nick: "jinbkim",
  avatar_url: `https://cdn.intra.42.fr/users/medium_jinbkim.jpg`,
  position: "mute"
}, {
  nick: "jinbkim",
  avatar_url: `https://cdn.intra.42.fr/users/medium_jinbkim.jpg`,
  position: "mute"
}, {
  nick: "jinbkim",
  avatar_url: `https://cdn.intra.42.fr/users/medium_jinbkim.jpg`,
  position: "mute"
}, {
  nick: "jinbkim",
  avatar_url: `https://cdn.intra.42.fr/users/medium_jinbkim.jpg`,
  position: "mute"
}, {
  nick: "jinbkim",
  avatar_url: `https://cdn.intra.42.fr/users/medium_jinbkim.jpg`,
  position: "mute"
}, {
  nick: "jinbkim",
  avatar_url: `https://cdn.intra.42.fr/users/medium_jinbkim.jpg`,
  position: "mute"
}, {
  nick: "jinbkim",
  avatar_url: `https://cdn.intra.42.fr/users/medium_jinbkim.jpg`,
  position: "mute"
}, {
  nick: "jinbkim",
  avatar_url: `https://cdn.intra.42.fr/users/medium_jinbkim.jpg`,
  position: "mute"
}, {
  nick: "jinbkim",
  avatar_url: `https://cdn.intra.42.fr/users/medium_jinbkim.jpg`,
  position: "mute"
}, {
  nick: "jinbkim",
  avatar_url: `https://cdn.intra.42.fr/users/medium_jinbkim.jpg`,
  position: "mute"
}, {
  nick: "last",
  avatar_url: `/public/users.svg`,
  position: "mute"
}];

export const chatLog = [{
  nick: "first",
  position: "admin",
  avatar_url: `https://cdn.intra.42.fr/users/medium_donglee.jpg`,
  time: new Date().getTime(),
  message: "first"
}, {
  nick: "yochoi",
  position: "owner",
  avatar_url: `https://cdn.intra.42.fr/users/medium_yochoi.png`,
  time: "2017-01-01T00:00:00.000Z",
  message: "ㅇㅇ"
}, {
  nick: "yochoi",
  position: "owner",
  avatar_url: `https://cdn.intra.42.fr/users/medium_yochoi.png`,
  time: "2017-01-01T00:00:00.000Z",
  message: "ㅇㅇ\n안녕하세요\n여러줄 테스트중\n긴줄테스터123412341234123412341234123412341234123412341234긴줄테스터123412341234123412341234123412341234123412341234"
}, {
  nick: "yochoi",
  position: "owner",
  avatar_url: `https://cdn.intra.42.fr/users/medium_yochoi.png`,
  time: "2017-01-01T00:00:00.000Z",
  message: "ㅇㅇ"
}, {
  nick: "yochoi",
  position: "owner",
  avatar_url: `https://cdn.intra.42.fr/users/medium_yochoi.png`,
  time: "2017-01-01T00:00:00.000Z",
  message: "ㅇㅇ"
}, {
  nick: "yochoi",
  position: "owner",
  avatar_url: `https://cdn.intra.42.fr/users/medium_yochoi.png`,
  time: "2017-01-01T00:00:00.000Z",
  message: "ㅇㅇ"
}, {
  nick: "yochoi",
  position: "owner",
  avatar_url: `https://cdn.intra.42.fr/users/medium_yochoi.png`,
  time: "2017-01-01T00:00:00.000Z",
  message: "ㅇㅇ"
}, {
  nick: "yochoi",
  position: "owner",
  avatar_url: `https://cdn.intra.42.fr/users/medium_yochoi.png`,
  time: "2017-01-01T00:00:00.000Z",
  message: "ㅇㅇ"
}, {
  nick: "yochoi",
  position: "owner",
  avatar_url: `https://cdn.intra.42.fr/users/medium_yochoi.png`,
  time: "2017-01-01T00:00:00.000Z",
  message: "ㅇㅇ"
}, {
  nick: "yochoi",
  position: "owner",
  avatar_url: `https://cdn.intra.42.fr/users/medium_yochoi.png`,
  time: "2017-01-01T00:00:00.000Z",
  message: "ㅇㅇ"
}, {
  nick: "yochoi",
  position: "owner",
  avatar_url: `https://cdn.intra.42.fr/users/medium_yochoi.png`,
  time: "2017-01-01T00:00:00.000Z",
  message: "ㅇㅇ"
}, {
  nick: "yochoi",
  position: "owner",
  avatar_url: `https://cdn.intra.42.fr/users/medium_yochoi.png`,
  time: "2017-01-01T00:00:00.000Z",
  message: "ㅇㅇ"
}, {
  nick: "yochoi",
  position: "owner",
  avatar_url: `https://cdn.intra.42.fr/users/medium_yochoi.png`,
  time: "2017-01-01T00:00:00.000Z",
  message: "ㅇㅇ"
}, {
  nick: "yochoi",
  position: "owner",
  avatar_url: `https://cdn.intra.42.fr/users/medium_yochoi.png`,
  time: "2017-01-01T00:00:00.000Z",
  message: "ㅇㅇ"
}, {
  nick: "yochoi",
  position: "owner",
  avatar_url: `https://cdn.intra.42.fr/users/medium_yochoi.png`,
  time: "2017-01-01T00:00:00.000Z",
  message: "ㅇㅇ"
}, {
  nick: "yochoi",
  position: "owner",
  avatar_url: `https://cdn.intra.42.fr/users/medium_yochoi.png`,
  time: "2017-01-01T00:00:00.000Z",
  message: "ㅇㅇ"
}, {
  nick: "yochoi",
  position: "owner",
  avatar_url: `https://cdn.intra.42.fr/users/medium_yochoi.png`,
  time: "2017-01-01T00:00:00.000Z",
  message: "ㅇㅇ"
}, {
  nick: "yochoi",
  position: "owner",
  avatar_url: `https://cdn.intra.42.fr/users/medium_yochoi.png`,
  time: "2017-01-01T00:00:00.000Z",
  message: "ㅇㅇ"
}, {
  nick: "yochoi",
  position: "owner",
  avatar_url: `https://cdn.intra.42.fr/users/medium_yochoi.png`,
  time: "2017-01-01T00:00:00.000Z",
  message: "ㅇㅇ"
}, {
  nick: "yochoi",
  position: "owner",
  avatar_url: `https://cdn.intra.42.fr/users/medium_yochoi.png`,
  time: "2017-01-01T00:00:00.000Z",
  message: "ㅇㅇ"
}, {
  nick: "yochoi",
  position: "owner",
  avatar_url: `https://cdn.intra.42.fr/users/medium_yochoi.png`,
  time: "2017-01-01T00:00:00.000Z",
  message: "ㅇㅇ"
}, {
  nick: "yochoi",
  position: "owner",
  avatar_url: `https://cdn.intra.42.fr/users/medium_yochoi.png`,
  time: "2017-01-01T00:00:00.000Z",
  message: "ㅇㅇ"
}, {
  nick: "yochoi",
  position: "owner",
  avatar_url: `https://cdn.intra.42.fr/users/medium_yochoi.png`,
  time: "2017-01-01T00:00:00.000Z",
  message: "ㅇㅇ"
}, {
  nick: "yochoi",
  position: "owner",
  avatar_url: `https://cdn.intra.42.fr/users/medium_yochoi.png`,
  time: "2017-01-01T00:00:00.000Z",
  message: "ㅇㅇ"
}, {
  nick: "yochoi",
  position: "owner",
  avatar_url: `https://cdn.intra.42.fr/users/medium_yochoi.png`,
  time: "2017-01-01T00:00:00.000Z",
  message: "ㅇㅇ"
}, {
  nick: "yochoi",
  position: "owner",
  avatar_url: `https://cdn.intra.42.fr/users/medium_yochoi.png`,
  time: "2017-01-01T00:00:00.000Z",
  message: "ㅇㅇ"
}, {
  nick: "yochoi",
  position: "owner",
  avatar_url: `https://cdn.intra.42.fr/users/medium_yochoi.png`,
  time: "2017-01-01T00:00:00.000Z",
  message: "ㅇㅇ"
}, {
  nick: "yochoi",
  position: "owner",
  avatar_url: `https://cdn.intra.42.fr/users/medium_yochoi.png`,
  time: "2017-01-01T00:00:00.000Z",
  message: "ㅇㅇ"
}, {
  nick: "donglee",
  position: "admin",
  avatar_url: `https://cdn.intra.42.fr/users/medium_donglee.jpg`,
  time: "2017-01-01T00:00:00.000Z",
  message: "저는 빡빡이 입니다."
}, {
  nick: "donglee",
  position: "admin",
  avatar_url: `https://cdn.intra.42.fr/users/medium_donglee.jpg`,
  time: "2017-01-01T00:00:00.000Z",
  message: "저는 빡빡이 입니다."
}, {
  nick: "donglee",
  position: "admin",
  avatar_url: `https://cdn.intra.42.fr/users/medium_donglee.jpg`,
  time: "2017-01-01T00:00:00.000Z",
  message: "저는 빡빡이 입니다."
}, {
  nick: "donglee",
  position: "admin",
  avatar_url: `https://cdn.intra.42.fr/users/medium_donglee.jpg`,
  time: "2017-01-01T00:00:00.000Z",
  message: "저는 빡빡이 입니다."
}, {
  nick: "donglee",
  position: "admin",
  avatar_url: `https://cdn.intra.42.fr/users/medium_donglee.jpg`,
  time: "2017-01-01T00:00:00.000Z",
  message: "저는 빡빡이 입니다."
}, {
  nick: "donglee",
  position: "admin",
  avatar_url: `https://cdn.intra.42.fr/users/medium_donglee.jpg`,
  time: "2017-01-01T00:00:00.000Z",
  message: "저는 빡빡이 입니다."
}, {
  nick: "donglee",
  position: "admin",
  avatar_url: `https://cdn.intra.42.fr/users/medium_donglee.jpg`,
  time: "2017-01-01T00:00:00.000Z",
  message: "저는 빡빡이 입니다."
}, {
  nick: "donglee",
  position: "admin",
  avatar_url: `https://cdn.intra.42.fr/users/medium_donglee.jpg`,
  time: "2017-01-01T00:00:00.000Z",
  message: "저는 빡빡이 입니다."
}, {
  nick: "donglee",
  position: "admin",
  avatar_url: `https://cdn.intra.42.fr/users/medium_donglee.jpg`,
  time: "2017-01-01T00:00:00.000Z",
  message: "저는 빡빡이 입니다."
}, {
  nick: "donglee",
  position: "admin",
  avatar_url: `https://cdn.intra.42.fr/users/medium_donglee.jpg`,
  time: "2017-01-01T00:00:00.000Z",
  message: "저는 빡빡이 입니다."
}, {
  nick: "donglee",
  position: "admin",
  avatar_url: `https://cdn.intra.42.fr/users/medium_donglee.jpg`,
  time: "2017-01-01T00:00:00.000Z",
  message: "저는 빡빡이 입니다."
}, {
  nick: "donglee",
  position: "admin",
  avatar_url: `https://cdn.intra.42.fr/users/medium_donglee.jpg`,
  time: "2017-01-01T00:00:00.000Z",
  message: "저는 빡빡이 입니다."
}, {
  nick: "donglee",
  position: "admin",
  avatar_url: `https://cdn.intra.42.fr/users/medium_donglee.jpg`,
  time: "2017-01-01T00:00:00.000Z",
  message: "저는 빡빡이 입니다."
}, {
  nick: "donglee",
  position: "admin",
  avatar_url: `https://cdn.intra.42.fr/users/medium_donglee.jpg`,
  time: "2017-01-01T00:00:00.000Z",
  message: "저는 빡빡이 입니다."
}, {
  nick: "donglee",
  position: "admin",
  avatar_url: `https://cdn.intra.42.fr/users/medium_donglee.jpg`,
  time: "2017-01-01T00:00:00.000Z",
  message: "저는 빡빡이 입니다."
}, {
  nick: "last",
  position: "admin",
  avatar_url: `https://cdn.intra.42.fr/users/medium_donglee.jpg`,
  time: "2017-01-01T00:00:00.000Z",
  message: "last."
}];